return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "1.0.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 100,
  tilewidth = 100,
  tileheight = 100,
  nextobjectid = 182,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      name = "MapObjects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "Player",
          type = "player",
          shape = "ellipse",
          x = 5030,
          y = 8642.4,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "graphicsSwitch",
          type = "switch",
          shape = "rectangle",
          x = 5030,
          y = 8641.6,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4893.26,
          y = 8728,
          width = 576.443,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4209.24,
          y = 7655.51,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 10,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4964,
          y = 8808.76,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 11,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5108.96,
          y = 8887.19,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 12,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5509.29,
          y = 8865.46,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 13,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5017.82,
          y = 8761.06,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 14,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5086.62,
          y = 8803.74,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 23,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5103.25,
          y = 7600.93,
          width = 444.039,
          height = 30.3548,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4482.91,
          y = 7833.73,
          width = 11.2964,
          height = 295.885,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3777.06,
          y = 7929.73,
          width = 393.957,
          height = 30.6058,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4364.69,
          y = 8000.27,
          width = 560.214,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4467.22,
          y = 7983.75,
          width = 80,
          height = 7.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5066.89,
          y = 7451.07,
          width = 565.547,
          height = 36.5686,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4727.73,
          y = 7513.78,
          width = 302.961,
          height = 15.1031,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5041.83,
          y = 7423.01,
          width = 444.039,
          height = 15.1031,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4689.08,
          y = 7301.28,
          width = 804.489,
          height = 106.472,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4519.82,
          y = 8306.79,
          width = 395.912,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4564.88,
          y = 8294.98,
          width = 334.729,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4838.45,
          y = 7890.14,
          width = 9,
          height = 458.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "linesSwitch",
          type = "switch",
          shape = "rectangle",
          x = 4210.81,
          y = 7769.9,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4242.44,
          y = 7574.49,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 78,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4188.91,
          y = 7574.24,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 79,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4207.58,
          y = 7539.58,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 80,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4252.91,
          y = 7519.58,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 81,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4182.24,
          y = 7492.91,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 82,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4212.91,
          y = 7474.24,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 83,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4133.33,
          y = 7632,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 84,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4288,
          y = 7620,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 85,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4852.67,
          y = 7876.16,
          width = 36,
          height = 605.016,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4255.38,
          y = 8382.33,
          width = 697.245,
          height = 64.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4767.33,
          y = 8274.83,
          width = 12,
          height = 460.175,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4900.83,
          y = 8707.33,
          width = 9,
          height = 146.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5160.83,
          y = 8202,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4770,
          y = 8828.67,
          width = 177.167,
          height = 5.33333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5239.38,
          y = 8018.33,
          width = 82.5783,
          height = 774,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4859.5,
          y = 8803.33,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5135.3,
          y = 8218.69,
          width = 236.062,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5160.64,
          y = 8133.36,
          width = 236.062,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5186.17,
          y = 8116.67,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5189.97,
          y = 8045.36,
          width = 236.062,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5215.5,
          y = 8028.67,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5145,
          y = 8328.83,
          width = 206.667,
          height = 27.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5202,
          y = 8404.83,
          width = 206.667,
          height = 27.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5214.94,
          y = 8300.67,
          width = 2.8936,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5195.27,
          y = 7336.29,
          width = 36,
          height = 364.664,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5132.88,
          y = 7681.17,
          width = 302.961,
          height = 8.35074,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5337.45,
          y = 7116.25,
          width = 73.2376,
          height = 770.893,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4422.11,
          y = 8035.04,
          width = 489.787,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3797.46,
          y = 7502.53,
          width = 70.3162,
          height = 676.19,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3782.27,
          y = 7964.41,
          width = 296.599,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3877.17,
          y = 7710.47,
          width = 11.2964,
          height = 295.885,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3776.76,
          y = 7718.1,
          width = 177.794,
          height = 17.5423,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3867,
          y = 6866,
          width = 759,
          height = 232.336,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3759.6,
          y = 7544.61,
          width = 221.007,
          height = 17.5423,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4970.56,
          y = 7217.26,
          width = 43.6258,
          height = 518.451,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4948.93,
          y = 7237.82,
          width = 503.774,
          height = 8.35074,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5030.46,
          y = 7413.57,
          width = 417.348,
          height = 1.99588,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4792.63,
          y = 7283.35,
          width = 14.3935,
          height = 364.664,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4960.39,
          y = 7285.89,
          width = 5.4967,
          height = 278.238,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5016.31,
          y = 7571.99,
          width = 24.5709,
          height = 26.0908,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 124,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5048.72,
          y = 7558.13,
          width = 24.5709,
          height = 26.0908,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 125,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5033.47,
          y = 7504.75,
          width = 24.5709,
          height = 26.0908,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 126,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5018.22,
          y = 7457.72,
          width = 24.5709,
          height = 26.0908,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 146,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4241,
          y = 7956,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 147,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4899,
          y = 7778,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 150,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5297,
          y = 7836,
          width = 444.039,
          height = 30.3548,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5310,
          y = 7829,
          width = 417.348,
          height = 1.99588,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5677,
          y = 7355,
          width = 21,
          height = 533.664,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5228,
          y = 8500,
          width = 611,
          height = 27.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3033,
          y = 7490,
          width = 873,
          height = 17.5423,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3712,
          y = 7473,
          width = 3,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3633,
          y = 7473,
          width = 3,
          height = 153,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3571,
          y = 7473,
          width = 3,
          height = 248,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3515.85,
          y = 7474,
          width = 3.14754,
          height = 331.541,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3449.75,
          y = 7474,
          width = 3.14754,
          height = 199.344,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3391,
          y = 7473,
          width = 3.14754,
          height = 115.41,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3311,
          y = 7511,
          width = 410,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "soundSwitch",
          type = "switch",
          shape = "rectangle",
          x = 2425.81,
          y = 5808.9,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "colorSwitch",
          type = "switch",
          shape = "rectangle",
          x = 5845,
          y = 5614,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "pathingSwitch",
          type = "switch",
          shape = "rectangle",
          x = 4791.81,
          y = 3550.9,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1102,
          y = 5173,
          width = 170,
          height = 2810,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 670,
          y = 5217,
          width = 635,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1026,
          y = 5860,
          width = 635,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 700,
          y = 6731,
          width = 635,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1091,
          y = 5201,
          width = 3.14754,
          height = 1387,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1076,
          y = 5203,
          width = 3.14754,
          height = 1094,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1288,
          y = 5812,
          width = 3.14754,
          height = 1034,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1590,
          y = 5852,
          width = 7.15,
          height = 146,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1306,
          y = 5734,
          width = 24.15,
          height = 351,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1038,
          y = 5982,
          width = 356.998,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "barriers",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 148,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 3157,
          y = 8179,
          width = 711,
          height = 1121,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 3805,
          y = 8447,
          width = 515,
          height = 862,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 5693,
          y = 7860,
          width = 1385,
          height = 656,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 4259,
          y = 8430,
          width = 516,
          height = 869,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 4687,
          y = 8834,
          width = 1309,
          height = 498,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 4906,
          y = 8747,
          width = 1165,
          height = 139,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 5291,
          y = 8517,
          width = 1411,
          height = 332,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 3037,
          y = 7498,
          width = 788,
          height = 811,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "lines",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 127,
          name = "",
          type = "",
          shape = "polyline",
          x = 4266.65,
          y = 8397.31,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -439.756, y = -374.936 }
          },
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "polyline",
          x = 4266.65,
          y = 8398.58,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -439.756, y = -458.821 }
          },
          properties = {}
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "polyline",
          x = 4264.11,
          y = 8401.12,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -419.42, y = -531.266 }
          },
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "polyline",
          x = 4267.92,
          y = 8399.85,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -424.504, y = -639.298 }
          },
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "polyline",
          x = 4266.65,
          y = 8394.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -418.149, y = -796.899 }
          },
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "polyline",
          x = 4273,
          y = 8394.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -310.005, y = -837.764 }
          },
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "polyline",
          x = 4266.65,
          y = 8396.03,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 101.678, y = -383.833 }
          },
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "polyline",
          x = 4271.73,
          y = 8398.58,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 189.375, y = -376.207 }
          },
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "polyline",
          x = 4273,
          y = 8389.68,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 330.452, y = -369.853 }
          },
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "polyline",
          x = 4271.73,
          y = 8393.49,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 433.401, y = -369.853 }
          },
          properties = {}
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "polyline",
          x = 4261.57,
          y = 8398.58,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 577.021, y = -368.582 }
          },
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "",
          shape = "polyline",
          x = 4264.11,
          y = 8397.31,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 604.982, y = -251.652 }
          },
          properties = {}
        },
        {
          id = 139,
          name = "",
          type = "",
          shape = "polyline",
          x = 4269.19,
          y = 8396.03,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 604.982, y = -88.968 }
          },
          properties = {}
        },
        {
          id = 140,
          name = "",
          type = "",
          shape = "polyline",
          x = 5244,
          y = 8040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -384, y = -100 }
          },
          properties = {}
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "polyline",
          x = 5245,
          y = 8035,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -445, y = -391 }
          },
          properties = {}
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "polyline",
          x = 5244,
          y = 8039,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -235, y = -431 }
          },
          properties = {}
        },
        {
          id = 143,
          name = "",
          type = "",
          shape = "polyline",
          x = 5239,
          y = 8029,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -32, y = -418 }
          },
          properties = {}
        },
        {
          id = 144,
          name = "",
          type = "",
          shape = "polyline",
          x = 5244,
          y = 8040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 114, y = -456 }
          },
          properties = {}
        }
      }
    }
  }
}
