return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "1.0.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 100,
  tilewidth = 100,
  tileheight = 100,
  nextobjectid = 306,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      name = "MapObjects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "Player",
          type = "player",
          shape = "ellipse",
          x = 5030,
          y = 8642.4,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "graphicsSwitch",
          type = "switch",
          shape = "rectangle",
          x = 5030,
          y = 8641.6,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4893.26,
          y = 8728,
          width = 576.443,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4209.24,
          y = 7655.51,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 10,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4964,
          y = 8808.76,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 11,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5108.96,
          y = 8887.19,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 12,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5509.29,
          y = 8865.46,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 13,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5017.82,
          y = 8761.06,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 14,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5086.62,
          y = 8803.74,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 31,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4482.91,
          y = 7833.73,
          width = 11.2964,
          height = 295.885,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3777.06,
          y = 7929.73,
          width = 393.957,
          height = 30.6058,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4364.69,
          y = 8000.27,
          width = 560.214,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4467.22,
          y = 7983.75,
          width = 80,
          height = 7.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5314,
          y = 7351.07,
          width = 318.437,
          height = 36.5686,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4727.73,
          y = 7513.78,
          width = 302.961,
          height = 15.1031,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5041.83,
          y = 7323.01,
          width = 444.039,
          height = 15.1031,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4690.08,
          y = 7254,
          width = 804.489,
          height = 51,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4519.82,
          y = 8306.79,
          width = 395.912,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4564.88,
          y = 8294.98,
          width = 334.729,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4838.45,
          y = 7890.14,
          width = 9,
          height = 458.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "linesSwitch",
          type = "switch",
          shape = "rectangle",
          x = 4210.81,
          y = 7769.9,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4242.44,
          y = 7574.49,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 78,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4188.91,
          y = 7574.24,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 79,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4207.58,
          y = 7539.58,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 80,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4252.91,
          y = 7519.58,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 81,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4182.24,
          y = 7492.91,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 82,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4212.91,
          y = 7474.24,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 83,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4133.33,
          y = 7632,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 84,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4288,
          y = 7620,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 85,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4852.67,
          y = 7876.16,
          width = 36,
          height = 605.016,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4255.38,
          y = 8382.33,
          width = 697.245,
          height = 64.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4767.33,
          y = 8274.83,
          width = 12,
          height = 460.175,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4900.83,
          y = 8707.33,
          width = 9,
          height = 146.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5160.83,
          y = 8202,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4770,
          y = 8828.67,
          width = 177.167,
          height = 5.33333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5239.38,
          y = 8018.33,
          width = 82.5783,
          height = 774,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4859.5,
          y = 8803.33,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5135.3,
          y = 8218.69,
          width = 236.062,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5160.64,
          y = 8133.36,
          width = 236.062,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5186.17,
          y = 8116.67,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5189.97,
          y = 8045.36,
          width = 236.062,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5215.5,
          y = 8028.67,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5145,
          y = 8328.83,
          width = 206.667,
          height = 27.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5202,
          y = 8404.83,
          width = 206.667,
          height = 27.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5214.94,
          y = 8300.67,
          width = 2.8936,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5337.45,
          y = 7005,
          width = 73.2376,
          height = 882.143,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4422.11,
          y = 8035.04,
          width = 489.787,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3797.46,
          y = 7502.53,
          width = 70.3162,
          height = 676.19,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3782.27,
          y = 7964.41,
          width = 296.599,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3877.17,
          y = 7710.47,
          width = 11.2964,
          height = 295.885,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3776.76,
          y = 7718.1,
          width = 177.794,
          height = 17.5423,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3846,
          y = 6544,
          width = 1634,
          height = 232.336,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3759.6,
          y = 7544.61,
          width = 221.007,
          height = 17.5423,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4970.56,
          y = 7098,
          width = 43.6258,
          height = 637.711,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4949.93,
          y = 7237.82,
          width = 503.774,
          height = 8.35074,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5030.46,
          y = 7313.57,
          width = 417.348,
          height = 1.99588,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4792.63,
          y = 7154,
          width = 14.3935,
          height = 494.014,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4960.39,
          y = 7201,
          width = 5.4967,
          height = 363.128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4925,
          y = 7598,
          width = 24.5709,
          height = 26.0908,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 124,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5227,
          y = 7746,
          width = 24.5709,
          height = 26.0908,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 125,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4869,
          y = 7591,
          width = 24.5709,
          height = 26.0908,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 126,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5277,
          y = 7765,
          width = 24.5709,
          height = 26.0908,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 146,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4241,
          y = 7956,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 147,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4899,
          y = 7778,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 150,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5297,
          y = 7836,
          width = 444.039,
          height = 30.3548,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5310,
          y = 7829,
          width = 417.348,
          height = 1.99588,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5677,
          y = 7355,
          width = 21,
          height = 533.664,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5228,
          y = 8500,
          width = 611,
          height = 27.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3033,
          y = 7490,
          width = 873,
          height = 17.5423,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3712,
          y = 7473,
          width = 3,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3633,
          y = 7473,
          width = 3,
          height = 153,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3571,
          y = 7473,
          width = 3,
          height = 248,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3515.85,
          y = 7474,
          width = 3.14754,
          height = 331.541,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3449.75,
          y = 7474,
          width = 3.14754,
          height = 199.344,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3391,
          y = 7473,
          width = 3.14754,
          height = 115.41,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3311,
          y = 7511,
          width = 410,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "soundSwitch",
          type = "switch",
          shape = "rectangle",
          x = 2493,
          y = 5956,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "colorSwitch",
          type = "switch",
          shape = "rectangle",
          x = 5845,
          y = 5614,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "pathingSwitch",
          type = "switch",
          shape = "rectangle",
          x = 4791.81,
          y = 3550.9,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1102,
          y = 5052,
          width = 170,
          height = 2931,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 672,
          y = 5270,
          width = 635,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1026,
          y = 5860,
          width = 635,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 700,
          y = 6731,
          width = 635,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1091,
          y = 5058,
          width = 3.14754,
          height = 1530,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1076,
          y = 5060,
          width = 3.14754,
          height = 1237,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1288,
          y = 5812,
          width = 3.14754,
          height = 1034,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1590,
          y = 5852,
          width = 7.15,
          height = 146,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1306,
          y = 5734,
          width = 24.15,
          height = 351,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1038,
          y = 5982,
          width = 356.998,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5182,
          y = 8036,
          width = 252,
          height = 7.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5153,
          y = 8124,
          width = 252,
          height = 7.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5128,
          y = 8209,
          width = 252,
          height = 7.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5220,
          y = 8295,
          width = 6.06,
          height = 194,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 980,
          y = 5100,
          width = 920,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1600,
          y = 5000,
          width = 600,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2900,
          y = 5000,
          width = 600,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3200,
          y = 5100,
          width = 600,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 193,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1339,
          y = 4773,
          width = 10,
          height = 1176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1238,
          y = 4900,
          width = 775,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1362,
          y = 4881,
          width = 5,
          height = 300,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1629,
          y = 4982,
          width = 7,
          height = 214,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1665,
          y = 4883,
          width = 9,
          height = 199,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1942,
          y = 4883,
          width = 7.15,
          height = 203,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3239,
          y = 4985,
          width = 7.15,
          height = 203,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3445,
          y = 4984,
          width = 7.15,
          height = 203,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3207,
          y = 5069,
          width = 287,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2666,
          y = 5816,
          width = 11,
          height = 508,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2154,
          y = 5832,
          width = 741,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2297,
          y = 5784,
          width = 18,
          height = 321,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2503,
          y = 6095,
          width = 417,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 208,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2682,
          y = 5820,
          width = 2,
          height = 475,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2655,
          y = 6248,
          width = 33,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2293,
          y = 5798,
          width = 2,
          height = 343,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2288,
          y = 6088,
          width = 33,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2207,
          y = 5817,
          width = 417,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 213,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2615,
          y = 5812,
          width = 4,
          height = 46,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 214,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 2428,
          y = 6091,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 252,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3937,
          y = 5424,
          width = 108,
          height = 1727.34,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 253,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3900,
          y = 4916,
          width = 600,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 254,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4145,
          y = 4800,
          width = 7.15,
          height = 203,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 255,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3907,
          y = 4885,
          width = 287,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 256,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3600,
          y = 4816,
          width = 600,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3939,
          y = 4801,
          width = 7.15,
          height = 203,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3693,
          y = 4800,
          width = 7.15,
          height = 386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3556,
          y = 4891,
          width = 169,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3579,
          y = 4871,
          width = 7.15,
          height = 310,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3563,
          y = 5079,
          width = 169,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1082,
          y = 3593,
          width = 1110,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1101,
          y = 3714,
          width = 1066,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1134,
          y = 3550,
          width = 79,
          height = 682,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1221,
          y = 3574,
          width = 2,
          height = 630,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1109,
          y = 3784,
          width = 648,
          height = 13,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 268,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1594,
          y = 3577,
          width = 8,
          height = 241,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 269,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1587,
          y = 3577,
          width = 2,
          height = 230,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1969,
          y = 2571,
          width = 88,
          height = 1247,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 273,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 143,
          y = 4138,
          width = 1162,
          height = 35,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 274,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 199,
          y = 4100,
          width = 79,
          height = 694,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 283,
          y = 4111,
          width = 5,
          height = 591,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 185,
          y = 4593,
          width = 132,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1901,
          y = 2603,
          width = 633,
          height = 19,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2399,
          y = 2557,
          width = 40,
          height = 475,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 2447,
          y = 2581,
          width = 2,
          height = 420,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1794,
          y = 2855,
          width = 681,
          height = 19,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 1958,
          y = 2577,
          width = 2,
          height = 420,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 2091.33,
          y = 5762,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 284,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 2278.33,
          y = 4957,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 285,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 2814.33,
          y = 4946,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 286,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 1283.33,
          y = 4648,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 287,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 3762.33,
          y = 5216,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 288,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 3850.33,
          y = 5348,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 289,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 1449.33,
          y = 6040,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 290,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 3858.33,
          y = 5879,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 291,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 2310,
          y = 6260,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["special"] = "sprinter",
            ["tag"] = "soundSwitch_enemies"
          }
        },
        {
          id = 292,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 2383,
          y = 6273,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["special"] = "sprinter",
            ["tag"] = "soundSwitch_enemies"
          }
        },
        {
          id = 293,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 2449,
          y = 6289,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["special"] = "sprinter",
            ["tag"] = "soundSwitch_enemies"
          }
        },
        {
          id = 294,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 2268,
          y = 6212,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["special"] = "sprinter",
            ["tag"] = "soundSwitch_enemies"
          }
        },
        {
          id = 295,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 2241,
          y = 6290,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["special"] = "sprinter",
            ["tag"] = "soundSwitch_enemies"
          }
        },
        {
          id = 296,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 2333,
          y = 6323,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["special"] = "sprinter",
            ["tag"] = "soundSwitch_enemies"
          }
        },
        {
          id = 304,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 5021,
          y = 7471,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 305,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 5293,
          y = 7476,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        }
      }
    },
    {
      type = "objectgroup",
      name = "gates",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 299,
          name = "graphicsGate",
          type = "gate",
          shape = "rectangle",
          x = 5010,
          y = 7682,
          width = 332,
          height = 49,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsGate"
          }
        },
        {
          id = 301,
          name = "linesGate",
          type = "gate",
          shape = "rectangle",
          x = 5010,
          y = 7628,
          width = 332,
          height = 49,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesGate"
          }
        },
        {
          id = 302,
          name = "soundGate",
          type = "gate",
          shape = "rectangle",
          x = 5010,
          y = 7574,
          width = 332,
          height = 49,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "soundGate"
          }
        }
      }
    },
    {
      type = "objectgroup",
      name = "barriers",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 148,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 3157,
          y = 8179,
          width = 711,
          height = 1121,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 3805,
          y = 8447,
          width = 515,
          height = 862,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 5693,
          y = 7860,
          width = 1385,
          height = 656,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 4259,
          y = 8430,
          width = 516,
          height = 869,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 4687,
          y = 8834,
          width = 1309,
          height = 498,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 4906,
          y = 8747,
          width = 1165,
          height = 139,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 5291,
          y = 8517,
          width = 1411,
          height = 332,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 176,
          y = 7498,
          width = 3649,
          height = 811,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = 74,
          y = 5305,
          width = 1047,
          height = 2208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 277,
          name = "Barrier",
          type = "barrier",
          shape = "rectangle",
          x = -900,
          y = 2903,
          width = 1146,
          height = 3430,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "lines",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 127,
          name = "",
          type = "",
          shape = "polyline",
          x = 4266.65,
          y = 8397.31,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -439.756, y = -374.936 }
          },
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "polyline",
          x = 4266.65,
          y = 8398.58,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -439.756, y = -458.821 }
          },
          properties = {}
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "polyline",
          x = 4264.11,
          y = 8401.12,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -419.42, y = -531.266 }
          },
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "polyline",
          x = 4267.92,
          y = 8399.85,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -424.504, y = -639.298 }
          },
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "polyline",
          x = 4266.65,
          y = 8394.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -418.149, y = -796.899 }
          },
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "polyline",
          x = 4273,
          y = 8394.76,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -310.005, y = -837.764 }
          },
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "polyline",
          x = 4266.65,
          y = 8396.03,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 101.678, y = -383.833 }
          },
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "polyline",
          x = 4271.73,
          y = 8398.58,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 189.375, y = -376.207 }
          },
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "polyline",
          x = 4273,
          y = 8389.68,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 330.452, y = -369.853 }
          },
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "polyline",
          x = 4271.73,
          y = 8393.49,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 433.401, y = -369.853 }
          },
          properties = {}
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "polyline",
          x = 4261.57,
          y = 8398.58,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 577.021, y = -368.582 }
          },
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "",
          shape = "polyline",
          x = 4264.11,
          y = 8397.31,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 604.982, y = -251.652 }
          },
          properties = {}
        },
        {
          id = 139,
          name = "",
          type = "",
          shape = "polyline",
          x = 4269.19,
          y = 8396.03,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 604.982, y = -88.968 }
          },
          properties = {}
        },
        {
          id = 140,
          name = "",
          type = "",
          shape = "polyline",
          x = 5244,
          y = 8040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -384, y = -100 }
          },
          properties = {}
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "polyline",
          x = 5245,
          y = 8035,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -445, y = -391 }
          },
          properties = {}
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "polyline",
          x = 5244,
          y = 8039,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -235, y = -431 }
          },
          properties = {}
        },
        {
          id = 143,
          name = "",
          type = "",
          shape = "polyline",
          x = 5239,
          y = 8029,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -72, y = -694 }
          },
          properties = {}
        },
        {
          id = 144,
          name = "",
          type = "",
          shape = "polyline",
          x = 5244,
          y = 8040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 114, y = -456 }
          },
          properties = {}
        },
        {
          id = 224,
          name = "",
          type = "",
          shape = "polyline",
          x = 3500,
          y = 7100,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -2300, y = 0 }
          },
          properties = {}
        },
        {
          id = 225,
          name = "",
          type = "",
          shape = "polyline",
          x = 3600,
          y = 7300,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -1532 }
          },
          properties = {}
        },
        {
          id = 226,
          name = "",
          type = "",
          shape = "polyline",
          x = 3700,
          y = 7300,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -2500, y = 0 }
          },
          properties = {}
        },
        {
          id = 227,
          name = "",
          type = "",
          shape = "polyline",
          x = 3700,
          y = 7400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -2500, y = 0 }
          },
          properties = {}
        },
        {
          id = 228,
          name = "",
          type = "",
          shape = "polyline",
          x = 3800,
          y = 7500,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -1658 }
          },
          properties = {}
        },
        {
          id = 229,
          name = "",
          type = "",
          shape = "polyline",
          x = 3700,
          y = 7500,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -1708 }
          },
          properties = {}
        },
        {
          id = 230,
          name = "",
          type = "",
          shape = "polyline",
          x = 3500,
          y = 7300,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -1535 }
          },
          properties = {}
        },
        {
          id = 231,
          name = "",
          type = "",
          shape = "polyline",
          x = 3500,
          y = 7200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -2300, y = 0 }
          },
          properties = {}
        },
        {
          id = 232,
          name = "",
          type = "",
          shape = "polyline",
          x = 3400,
          y = 7100,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -1306 }
          },
          properties = {}
        },
        {
          id = 233,
          name = "",
          type = "",
          shape = "polyline",
          x = 3300,
          y = 7100,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -1246 }
          },
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "",
          shape = "polyline",
          x = 3300,
          y = 7000,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -2100, y = 0 }
          },
          properties = {}
        },
        {
          id = 236,
          name = "",
          type = "",
          shape = "polyline",
          x = 3300,
          y = 6900,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -2100, y = 0 }
          },
          properties = {}
        },
        {
          id = 237,
          name = "",
          type = "",
          shape = "polyline",
          x = 3200,
          y = 6900,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -975 }
          },
          properties = {}
        },
        {
          id = 238,
          name = "",
          type = "",
          shape = "polyline",
          x = 3100,
          y = 6900,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -931 }
          },
          properties = {}
        },
        {
          id = 239,
          name = "",
          type = "",
          shape = "polyline",
          x = 3100,
          y = 6800,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -1900, y = 0 }
          },
          properties = {}
        },
        {
          id = 240,
          name = "",
          type = "",
          shape = "polyline",
          x = 3100,
          y = 6700,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -1900, y = 0 }
          },
          properties = {}
        },
        {
          id = 241,
          name = "",
          type = "",
          shape = "polyline",
          x = 3000,
          y = 6700,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -718 }
          },
          properties = {}
        },
        {
          id = 242,
          name = "",
          type = "",
          shape = "polyline",
          x = 2900,
          y = 6700,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -720 }
          },
          properties = {}
        },
        {
          id = 243,
          name = "",
          type = "",
          shape = "polyline",
          x = 2900,
          y = 6600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -1700, y = 0 }
          },
          properties = {}
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "polyline",
          x = 2900,
          y = 6500,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -1700, y = 0 }
          },
          properties = {}
        },
        {
          id = 245,
          name = "",
          type = "",
          shape = "polyline",
          x = 2800,
          y = 6500,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -541 }
          },
          properties = {}
        },
        {
          id = 246,
          name = "",
          type = "",
          shape = "polyline",
          x = 2700,
          y = 6500,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0, y = -581 }
          },
          properties = {}
        },
        {
          id = 247,
          name = "",
          type = "",
          shape = "polyline",
          x = 2700,
          y = 6400,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -1500, y = 0 }
          },
          properties = {}
        },
        {
          id = 248,
          name = "",
          type = "",
          shape = "polyline",
          x = 2700,
          y = 6300,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -1500, y = 0 }
          },
          properties = {}
        },
        {
          id = 249,
          name = "",
          type = "",
          shape = "polyline",
          x = 2674,
          y = 5860,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 26, y = 59 },
            { x = 126, y = 99 },
            { x = 226, y = 120 },
            { x = 326, y = 122 },
            { x = 426, y = 109 },
            { x = 526, y = 65 },
            { x = 626, y = -6 },
            { x = 726, y = -66 },
            { x = 826, y = -95 },
            { x = 926, y = -92 },
            { x = 1026, y = -68 },
            { x = 1126, y = -18 }
          },
          properties = {}
        }
      }
    }
  }
}
