return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "1.0.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 100,
  tilewidth = 100,
  tileheight = 100,
  nextobjectid = 108,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      name = "MapObjects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "Player",
          type = "player",
          shape = "ellipse",
          x = 5030,
          y = 8642.4,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "graphicsSwitch",
          type = "switch",
          shape = "rectangle",
          x = 5030,
          y = 8641.6,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4893.26,
          y = 8728,
          width = 576.443,
          height = 28,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4209.24,
          y = 7655.51,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 10,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4964,
          y = 8808.76,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 11,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5108.96,
          y = 8887.19,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 12,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5509.29,
          y = 8865.46,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 13,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5017.82,
          y = 8761.06,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 14,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 5086.62,
          y = 8803.74,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "graphicsSwitch_followers"
          }
        },
        {
          id = 23,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4949.46,
          y = 7600.93,
          width = 302.961,
          height = 30.3548,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4726.62,
          y = 7563.42,
          width = 247.804,
          height = 106.472,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4139.75,
          y = 8084.11,
          width = 160,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3883.82,
          y = 7628.51,
          width = 13.9371,
          height = 371.226,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4298.6,
          y = 8000.27,
          width = 320,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4017.3,
          y = 8000.27,
          width = 80,
          height = 7.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3902.57,
          y = 7540.81,
          width = 13.9371,
          height = 371.226,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3922.98,
          y = 7600.1,
          width = 13.9371,
          height = 371.226,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3941.73,
          y = 7512.4,
          width = 13.9371,
          height = 371.226,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3961.59,
          y = 7570.32,
          width = 13.9371,
          height = 371.226,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 3980.34,
          y = 7482.62,
          width = 13.9371,
          height = 371.226,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5004.61,
          y = 7479.03,
          width = 247.804,
          height = 106.472,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4727.73,
          y = 7513.78,
          width = 302.961,
          height = 30.3548,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4951.67,
          y = 7423.18,
          width = 302.961,
          height = 30.3548,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5006.82,
          y = 7301.28,
          width = 247.804,
          height = 106.472,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4729.94,
          y = 7336.03,
          width = 302.961,
          height = 30.3548,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4728.83,
          y = 7385.67,
          width = 247.804,
          height = 106.472,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4519.82,
          y = 8306.79,
          width = 395.912,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4564.88,
          y = 8294.98,
          width = 334.729,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4838.45,
          y = 7890.14,
          width = 9,
          height = 458.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "linesSwitch",
          type = "switch",
          shape = "rectangle",
          x = 4210.81,
          y = 7769.9,
          width = 40,
          height = 35.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4242.44,
          y = 7574.49,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 78,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4188.91,
          y = 7574.24,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 79,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4207.58,
          y = 7539.58,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 80,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4252.91,
          y = 7519.58,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 81,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4182.24,
          y = 7492.91,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 82,
          name = "Follower",
          type = "follower",
          shape = "ellipse",
          x = 4212.91,
          y = 7474.24,
          width = 46.1774,
          height = 46.1774,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 83,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4133.33,
          y = 7632,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 84,
          name = "Snatcher",
          type = "snatcher",
          shape = "ellipse",
          x = 4288,
          y = 7620,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["tag"] = "linesSwitch_enemies"
          }
        },
        {
          id = 85,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4852.67,
          y = 7876.16,
          width = 36,
          height = 605.016,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4255.38,
          y = 8382.33,
          width = 697.245,
          height = 64.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4767.33,
          y = 8274.83,
          width = 12,
          height = 497.016,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4900.83,
          y = 8707.33,
          width = 9,
          height = 146.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5160.83,
          y = 8202,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4791.5,
          y = 8828.67,
          width = 155.667,
          height = 5.33333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5239.38,
          y = 8018.33,
          width = 82.5783,
          height = 774,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 4859.5,
          y = 8803.33,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5135.3,
          y = 8218.69,
          width = 236.062,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5160.64,
          y = 8133.36,
          width = 236.062,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5186.17,
          y = 8116.67,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5189.97,
          y = 8045.36,
          width = 236.062,
          height = 2.6122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5215.5,
          y = 8028.67,
          width = 9,
          height = 92,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5145,
          y = 8328.83,
          width = 206.667,
          height = 27.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5202,
          y = 8404.83,
          width = 206.667,
          height = 27.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5214.94,
          y = 8300.67,
          width = 2.8936,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5195.27,
          y = 7336.29,
          width = 36,
          height = 364.664,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5132.88,
          y = 7681.17,
          width = 302.961,
          height = 8.35074,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "Wall",
          type = "wall",
          shape = "rectangle",
          x = 5337.45,
          y = 7116.25,
          width = 73.2376,
          height = 770.893,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
